# Generated by Django 4.2.3 on 2023-09-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
