# Generated by Django 4.2.3 on 2023-09-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
